syntax = "proto3";
package splitsecure.keys.v1;

import "google/protobuf/empty.proto";

message AES {
  enum Length {
    LENGTH_UNSPECIFIED = 0;
    LENGTH_128 = 1;
    LENGTH_256 = 2;
  }

  AESBlockMode block_mode = 1;
  Length length = 2;
}

message AESBlockMode {
  oneof mode {
    google.protobuf.Empty ecb = 1;
    google.protobuf.Empty cbc = 2;
    BlockModeGCM gcm = 3;
    BlockModeCCM ccm = 4;
  }
}

message BlockModeGCM {
  // there is no optonality with regards to nonce size or tag length
  // the values to comply with FIPS-140-3 are used (respectively 96 and 128 bits).
}

message BlockModeCCM {}
