syntax = "proto3";
package splitsecure.keys.v1;

import "google/protobuf/empty.proto";

message SignatureSpec {
  oneof union {
    ECDSA ecdsa = 1;
    EDDSA eddsa = 2;
    MLDSA mldsa = 3; // FIPS 204
    RSA rsa = 4;
  }
}

enum ECDSA {
  ECDSA_UNSPECIFIED = 0;
  // NIST curves
  ECDSA_NIST_P224 = 1;
  ECDSA_NIST_P256 = 2;
  ECDSA_NIST_P384 = 3;
  ECDSA_NIST_P521 = 4;

  // NIST pseudorandom curves
  ECDSA_NIST_B233 = 5;
  ECDSA_NIST_B283 = 6;
  ECDSA_NIST_B409 = 7;
  ECDSA_NIST_B571 = 8;

  // NIST Koblitz curves
  ECDSA_NIST_K233 = 9;
  ECDSA_NIST_K283 = 10;
  ECDSA_NIST_K409 = 11;
  ECDSA_NIST_K571 = 12;

  // SEC curves
  ECDSA_SEC_P192K1 = 13;
  ECDSA_SEC_P224K1 = 14;
  ECDSA_SEC_P256K1 = 15;

  // Brainpool curves
  ECDSA_BRAINPOOL_P256R1 = 16;
  ECDSA_BRAINPOOL_P384R1 = 17;
  ECDSA_BRAINPOOL_P512R1 = 18;
}

message EDDSA {
  oneof union {
    ED25519 ed25519 = 1;
    ED448 ed448 = 2;
  }

  message ED25519 {}
  message ED448 {}
}

message MLDSA {
  oneof union {
    google.protobuf.Empty v44 = 1;
    google.protobuf.Empty v65 = 2;
    google.protobuf.Empty v87 = 3;
  }
}

message RSA {
  uint32 bits = 1;
  SignatureScheme signature_scheme = 2;

  enum SignatureScheme {
    SIGNATURE_SCHEME_UNSPECIFIED = 0;
    SIGNATURE_SCHEME_PKCS1V15 = 1;
    SIGNATURE_SCHEME_PSS = 2;
  }
}
